changes in response to review comments

diff --git a/scripts/outer/kubectl-kubestellar-prep_for_syncer b/scripts/outer/kubectl-kubestellar-prep_for_syncer
--- a/scripts/outer/kubectl-kubestellar-prep_for_syncer
+++ b/scripts/outer/kubectl-kubestellar-prep_for_syncer
@@ -134,7 +134,7 @@ spaceID=$(kubectl "${kubectl_flags[@]}" get synctargets.edge.kubestellar.io "$st
 
 kubectl ws "${kubectl_flags[@]}" "$espw"
 if ! cluster_ns_name="$(kubectl "${kubectl_flags[@]}" -n kubestellar get configmap kbmap-"$spaceID" -ojsonpath="{.metadata.labels['kubestellar\.io\/kube-bind-id']}")"; then
-	echo "error reading kube-bind cluster namespace from the configmap"
+	echo "error reading kube-bind cluster namespace from ConfigMap kbmap-$spaceID" >&2
 	exit 1
 fi
 prefixed_stname="$cluster_ns_name"-"$stname"
@@ -177,15 +177,12 @@ echo "now that workspace _exists_, but is it _ready_?"
 sleep 5
 
 if ! kubectl ws "${kubectl_flags[@]}" "$mbwsname" &> /dev/null; then
-	kubectl ws .
-	echo "tried once to switch to $mbwsname"
+    echo "tried once to switch to $mbwsname"
     sleep 15
     if ! kubectl ws "${kubectl_flags[@]}" "$mbwsname" &> /dev/null; then
-	kubectl ws .
-	echo "tried twice to switch to $mbwsname"
-	sleep 15
-	kubectl ws .
-	kubectl ws "${kubectl_flags[@]}" "$mbwsname"
+        echo "tried twice to switch to $mbwsname"
+        sleep 15
+        kubectl ws "${kubectl_flags[@]}" "$mbwsname"
     fi
 fi
 
