fix syncer space id
Signed-off-by: Ezra Silvera <ezra@il.ibm.com>

diff --git a/scripts/outer/kubectl-kubestellar-prep_for_syncer b/scripts/outer/kubectl-kubestellar-prep_for_syncer
--- a/scripts/outer/kubectl-kubestellar-prep_for_syncer
+++ b/scripts/outer/kubectl-kubestellar-prep_for_syncer
@@ -142,16 +142,15 @@ else
     kubectl ws "${kubectl_flags[@]}" "${rootws}:${imw}"
 fi
 kubectl ws "${kubectl_flags[@]}" "${rootws}:${imw}"
-spaceID=$(kubectl "${kubectl_flags[@]}" get synctargets.edge.kubestellar.io "$stname" -o jsonpath="{.metadata.annotations['kcp\.io/cluster']}")
 
 kubectl ws "${kubectl_flags[@]}" "${rootws}:${espw}"
-if ! cluster_ns_name="$(kubectl "${kubectl_flags[@]}" -n kubestellar get configmap kbmap-"$spaceID" -ojsonpath="{.metadata.labels['kubestellar\.io\/kube-bind-id']}")"; then
-	echo "error reading kube-bind cluster namespace from ConfigMap kbmap-$spaceID" >&2
+if ! cluster_ns_name="$(kubectl "${kubectl_flags[@]}" -n kubestellar get configmap kbmap-"$imw" -ojsonpath="{.metadata.labels['kubestellar\.io\/kube-bind-id']}")"; then
+	echo "error reading kube-bind cluster namespace from ConfigMap kbmap-$imw" >&2
 	exit 1
 fi
 prefixed_stname="$cluster_ns_name"-"$stname"
 stUID=$(kubectl "${kubectl_flags[@]}" get synctargets.edge.kubestellar.io $prefixed_stname -o jsonpath="{.metadata.uid}")
-mbwsname="$spaceID"-mb-"$stUID"
+mbwsname="$imw"-mb-"$stUID"
 
 espw_space_config="${PWD}/temp-space-config/spaceprovider-default-${espw}"
 kubectl-kubestellar-get-config-for-space --space-name ${espw} --provider-name default --sm-core-config $SM_CONFIG --sm-context $SM_CONTEXT --output $espw_space_config
