Update the kcp check

diff --git a/scripts/kubestellar b/scripts/kubestellar
--- a/scripts/kubestellar
+++ b/scripts/kubestellar
@@ -84,12 +84,23 @@ process_running() {
   fi
 }
 
-# Check if kcp is running
-if [ $(process_running kcp) != "running" ]
-then
-    echo "kcp is not running - please start it ...."
+# Check if kcp is running and can be reached
+if [ $(process_running kcp) != "running" ] ; then
+    echo "WARNING: kcp process does not seem to be running!"
+fi
+if ! kubectl get workspaces &> /dev/null ; then
+    echo "ERROR: KUBECONFIG does not seem to refer to kcp admin.kubeconfig!"
     exit 1
 fi
+if ! kubectl ws . --short &> /dev/null ; then
+    echo "ERROR: Unable to use the ws plugin, please make sure that it is in the PATH!"
+    exit 1
+fi
+if ! kubectl ws root:compute &> /dev/null ; then
+    echo "ERROR: Unable to switch to the root:compute workspace, kcp may not have completed its initialization!"
+    exit 1
+fi
+
 
 function create_or_replace() { # usage: filename
     filename="$1"
