Improve `kubestellar init` wrt waiting for kcp
(1) Make waiting for a process optional.
(2) Add non-optional waiting for the server to be fully ready.

Signed-off-by: Mike Spreitzer <mspreitz@us.ibm.com>

diff --git a/scripts/kubestellar b/scripts/kubestellar
--- a/scripts/kubestellar
+++ b/scripts/kubestellar
@@ -24,6 +24,7 @@
 # Requirements:
 #    Download KubeStellar binaries
 #    KubeStellar controller binaries are on $PATH.
+#    kubectl is configured to talk to kcp server with high privilege
 
 bindir="$(dirname "$0")"
 
@@ -37,6 +38,7 @@ remove=0
 cleanup=0
 espw_name="espw"
 log_folder=$(pwd)/kubestellar-logs
+local_kcp=true
 
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
@@ -49,6 +51,11 @@ while (( $# > 0 )); do
         then { log_folder="$2"; shift; }
         else { echo "$0: missing log folder" >&2; exit 1; }
         fi;;
+    (--local-kcp)
+        if (( $# > 1 ));
+        then { local_kcp="$2"; shift; }
+        else { echo "$0: missing log folder" >&2; exit 1; }
+        fi;;
     (--verbose|-V)
         verbosity=1
 	verbdir="";;
@@ -56,7 +63,7 @@ while (( $# > 0 )); do
 	xflag="-X"
 	set -x;;
     (-h|--help)
-        echo "Usage: $0 [init | start | stop] [--log-folder log_folder] [-V|--verbose] [-X]"
+        echo "Usage: $0 [init | start | stop] [--log-folder log_folder] [--local-kcp bool] [-V|--verbose] [-X]"
         exit 0;;
     (-*)
         echo "$0: unknown flag" >&2 ; exit 1;
@@ -73,6 +80,13 @@ if [ "$subcommand" == "" ]; then
     exit 1
 fi
 
+case "$local_kcp" in
+    (true|false) ;;
+    (*) echo "$0: --local-kcp must be given 'true' or 'false', not '${local_kcp}'" >&2
+	exit 1;;
+esac
+
+
 # Check if a given process name is running
 process_running() {
   SERVICE="$1"
@@ -83,13 +97,6 @@ process_running() {
       echo "stopped" 
   fi
 }
-
-# Check if kcp is running
-if [ $(process_running kcp) != "running" ]
-then
-    echo "kcp is not running - please start it ...."
-    exit 1
-fi
 
 function create_or_replace() { # usage: filename
     filename="$1"
@@ -103,10 +110,6 @@ function create_or_replace() { # usage: filename
     
 # current ws at start does not matter, is root:compute on return
 function ensure_root_compute_configd() {
-    if ! kubectl ws root:compute &> /dev/null ; then
-	echo "$0: Something is very wrong, unable to set current kcp workspace to root:compute" >&2
-	exit 1
-    fi
     ( cd ${SCRIPT_DIR}/../config/kube/exports/namespaced
       # Some are too big to `kubectl apply`
       for rsfn in apiresourceschema-*.yaml; do
@@ -301,6 +304,21 @@ if [ $subcommand == stop ]; then
    echo "kubestellar stopped ....."
    exit 0
 fi
+
+# Check if kcp is running
+if [ "$local_kcp" == true ] && [ $(process_running kcp) != "running" ]; then
+    echo "kcp is not running - please start it ...."
+    exit 1
+fi
+
+let tries=1
+while ! ( kubectl get workspaces && kubectl ws root:compute ); do
+    if (( ( tries & (tries-1) ) == 0 ))
+    then echo "$0: At $(date), kcp server not running yet or root:compute workspace not yet ready, waiting $(( tries * 15 )) sec..." >& 2
+    fi
+    let tries=tries+1
+    sleep 15
+done
 
 ensure_root_compute_configd
 ensure_espw
