update to pull_request_target

diff --git a/.github/workflows/docs-ecutable-syncer.yml b/.github/workflows/docs-ecutable-syncer.yml
--- a/.github/workflows/docs-ecutable-syncer.yml
+++ b/.github/workflows/docs-ecutable-syncer.yml
@@ -4,7 +4,7 @@ on:
   # So we can trigger manually if needed
   workflow_dispatch:
   # To confirm any changes to docs build successfully, without deploying them
-  pull_request:
+  pull_request_target:
     branches:
       - main
       - "release-*"
@@ -61,7 +61,18 @@ jobs:
       - name: echo fetching push or pull_request branch
         run: git fetch origin ${{ github.ref_name }}
         # run: echo running on branch ${{ github.ref_name }}
-        if: github.event_name == 'push' || github.event_name == 'pull_request'
+        if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
+
+      # - name: Check for Makefile
+      #   id: check_makefile
+      #   if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
+      #   run: |
+      #     if [[ -f "Makefile" ]]; then
+      #       echo "Makefile found"
+      #       exit 1
+      #     else
+      #       echo "Makefile not found"
+      #     fi
 
       - uses: actions/setup-go@v4
         with:
