add check for makefile

diff --git a/.github/workflows/docs-ecutable-mailbox.yml b/.github/workflows/docs-ecutable-mailbox.yml
--- a/.github/workflows/docs-ecutable-mailbox.yml
+++ b/.github/workflows/docs-ecutable-mailbox.yml
@@ -61,6 +61,17 @@ jobs:
         # run: echo running on branch ${{ github.ref_name }}
         if: github.event_name == 'push' || github.event_name == 'pull_request'
 
+      - name: Check for Makefile
+        id: check_makefile
+        if: github.event_name == 'pull_request'
+        run: |
+          if [[ -f "Makefile" ]]; then
+            echo "Makefile found"
+            exit 1
+          else
+            echo "Makefile not found"
+          fi
+
       - uses: actions/setup-go@v4
         with:
           go-version: v1.19
